name: Zealy Debug Run
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and Playwright
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
          pip install playwright
          playwright install --with-deps chromium

      - name: Run Zealy debug script
        run: |
          python -V
          python utils/scrapers/zealy_debug.py || true

      - name: Upload debug artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zealy-debug-artifacts
          path: |
            zealy_debug.png
            zealy_debug.html
            zealy_network.log
