name: Zealy Debug Run
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.42.0-jammy

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pip and install Playwright Python (match container) + other deps (exclude playwright)
        run: |
          python -m pip install --upgrade pip
          # Install the Playwright Python package that matches the container/browsers
          pip install "playwright==1.42.0"
          # Install other requirements but do not reinstall playwright from requirements.txt (case-insensitive)
          if [ -f requirements.txt ]; then
            grep -i -v '^playwright' requirements.txt > /tmp/req-no-playwright.txt || true
            if [ -s /tmp/req-no-playwright.txt ]; then
              pip install --no-cache-dir -r /tmp/req-no-playwright.txt
            fi
          fi

      - name: Diagnostic: show python and playwright presence
        run: |
          python -V
          python -c "import importlib; print('playwright present:', importlib.util.find_spec('playwright') is not None)"
          python -c "import playwright; print('playwright version:', getattr(playwright, '__version__', 'unknown'))" || true

      - name: Run Zealy debug script
        run: |
          python -V
          python utils/scrapers/zealy_debug.py || true

      - name: Upload debug artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zealy-debug-artifacts
          path: |
            zealy_debug.png
            zealy_debug.html
            zealy_network.log
