name: Zealy Debug Run
on:
  workflow_dispatch:

jobs:
  debug:
    # Use the Playwright image matching the version pinned in requirements.txt
    runs-on: ubuntu-latest
    container:
      # Use the specific Playwright image that matches playwright==1.42.0
      image: mcr.microsoft.com/playwright/python:v1.42.0-jammy

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show Python and Playwright info (diagnostic)
        run: |
          python -V
          python -c "import sys; print('PYTHONPATH:', sys.path[:3])" || true
          # Try to import playwright and print version (will fail if package not present)
          python -c "import importlib, pkgutil; print('playwright present:', importlib.util.find_spec('playwright') is not None); \
            import pkgutil; print('playwright pkgutil:', pkgutil.find_loader('playwright'))" || true
          python -c "import playwright; print('playwright version:', getattr(playwright, '__version__', 'no __version__'))" || true

      - name: Install requirements (exclude playwright)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            # remove any 'playwright' line (case-insensitive) so we don't reinstall browsers or cause version mismatch
            grep -i -v '^playwright' requirements.txt > /tmp/req-no-playwright.txt || true
            if [ -s /tmp/req-no-playwright.txt ]; then
              pip install --no-cache-dir -r /tmp/req-no-playwright.txt
            fi
          fi

      - name: Run Zealy debug script
        run: |
          python -V
          python -c "import playwright; print('playwright import OK, version:', getattr(playwright, '__version__', 'unknown'))" || true
          python utils/scrapers/zealy_debug.py || true

      - name: Upload debug artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zealy-debug-artifacts
          path: |
            zealy_debug.png
            zealy_debug.html
            zealy_network.log
